### ISSUE TITLE
E$$ENTIAL MEDICINE$ launch

### ISSUE THREAD

**Issue by yaelago** [TheBreakingGoodProject/Essential-Medicines#1]
We are launching E$$ENTIAL MEDICINE$ project today - A new citizen science project for exploring the world’s most important medicines.
I am excited to see how this public database evolves and works to improve the understanding of essential medicine accessibility for people around the world.

**Comment by kym834** [comment]
:raised_hands: Woohoo!! E$$ENTIAL MEDICINE$ is now open for contributions! :smiley::smiley:

@yaelago I'm also super excited to see how this project evolves and can't wait to see where it goes. 

A big congratulations to all the Breaking Good team :clap:  and thanks for all your help getting this project up and running and out there :pray:

**Comment by IngaTopolnicki** [comment]
Hi, I haven't used Github for years so am not really sure how it works. I have a question about one of the generic medicines I am trying to insert into the Google form. Where would be the best place for me to ask questions about the project? Thanks :)

**Comment by yaelago** [comment]
Hi @IngaTopolnicki , This would be the place to post your questions and engage in conversation!
You can post your question as a comment here, or open a new issue, using the green button on the top right.

**Comment by IngaTopolnicki** [comment]
@yaelago Thanks! I am looking to see if there are any generic medicines for a amphotericin b 3% _cream_. There is one that is a amphotericin b 3% _lotion_. Is there are difference between a cream, a lotion and say, an ointment? Should I include the lotion as a generic form of the new cream?

**Comment by kym834** [comment]
Hi @IngaTopolnicki! Small and subtle, the difference between creams, lotions and ointments is all in the water content. These products are therefore very similar but they do have different dosage forms so we would not consider the lotion to be a generic of the cream. Hope this helps :)

**Comment by IngaTopolnicki** [comment]
Thank you @kym834!

**Comment by liapaola** [comment]
Good morning all, I did azithromycin 2 days ago and I'd like to flag that it took _way_ longer than 30min (all in all, it was more about 45 and took 4 different sets of forms to submit it all). It was also not immediately clear that you couldn't do it all in one single form but you had to submit and open a new one. Maybe it would be good making it clear at the start? Hope this helps :-)

**Comment by yaelago** [comment]
Thanks @liapaola for this important feedback. We will amend the form with the updated time estimation and also make it clearer that for these medicines, which take longer to fill in, a few forms are needed to complete the task.

**Comment by TLMac** [comment]
Never used GitHub.  Finished phase 1 of Essential Meds.  How do I commit to staying in the project?  I do get the emails.

**Comment by yaelago** [comment]
Hi @TLMac , Thank you so much for your contributions and for your commitment to E$$ENTIAL MEDICINE$. 
You came to the right place :) This is the place where we discuss our project progress and next stages. Browse through the various issues on the top to learn about our activities and join the conversation.
Once Phase II in ready for contributions, we will post it here, and inform you by email.

If you are new to GitHub, and want to learn how to navigate it, you are welcome to check out our 
[How To Guide](https://github.com/TheBreakingGoodProject/GitHub-How-To-Guide).
