### ISSUE TITLE
National Science Week

### ISSUE THREAD

**Issue by yaelago** [TheBreakingGoodProject/Essential-Medicines#12]
Hi everyone!
Its National Science Week and E$$ENTIAL MEDICINE$ has a couple of exciting activities coming up - 

- A Panel Discussion on Aug 18th starting at 18:00 and followed by a 2 hour mini-hachathon
https://www.scienceweek.net.au/event/essential-medicines-panel

- A 12-Hour Hackathon on Aug 20th starting at 10:00
https://www.scienceweek.net.au/event/essential-medicines-hackathon

We'd love to see you at our events where we will present our new set of challenges for investigating the world's most important medicines! Start participating now at-  https://bit.ly/essmed

**Comment by yaelago** [comment]
Participating in our National Science Week challenges and have some questions / suggestions / new ideas ? 
This is the place to share them with the E$$ENTIAL MEDICINE$ community!

We love to hear your thoughts and engage in conversation!

**Comment by kym834** [comment]
An interesting and thought provoking finding during our price hikes$ challenge this evening by an anonymous participant who was looking at ribavirin.

"Hi there, I've just submitted analysis for the price hikes challenge for aerosolised ribavirin. It seems like aerosolised ribavirin isn't on the PBS, only tablets, so it's not a direct comparison. Still worth looking at, though. Frankly, $10 per 400mg ribavirin tablet still feels like a rip-off. It's an old, ooooold drug that any postgrad chemist could make with their eyes shut." 

This is a common trend we think we will come across often during this project. Many of the essential medicines have been around for years and how to make them has been nailed down to a tee!

Did you find a similar thing? Reply below to let us know :)

**Comment by GFirmer** [comment]
## National Science Week (updated 25 September 2020)

During National Science Week here in Australia the E$$ENTIAL MEDICINE$ team and The Breaking Good Project hosted an expert panel discussion on the world's most important medicines - the essential medicines. The panel discussed some of the barriers to accessing the essential medicines and how we might be able to break down these barrier. The event was recorded and is now up on our YouTube channel. [Check it out here](https://www.youtube.com/watch?v=dPKQyR5xYT0&t=11s&ab_channel=BreakingGood).
