### ISSUE TITLE
Open for contributions - Stage II

### ISSUE THREAD

**Issue by kym834** [TheBreakingGoodProject/Essential-Medicines#6]
We have launched the second stage of E$$ENTIAL MEDICINE$ today!! :tada:

This stage focuses on building upon the data we collected in Stage I to build a Circle of Life for each of the essential medicines that will then be added to our public database. 

If you have a questions or queries about Stage II, you can ask the E$$ENTIAL MEDICINE$ community and Breaking Good team by commenting below.

We can't wait to continue this journey with you all and are excited to see where this ends up :)

**Comment by yaelago** [comment]
To contribute to the Circle of Life click [here](https://redcap.sydney.edu.au/surveys/index.php?s=4WDFKF8PJM) and follow the instructions in the form.

Want to learn more about what we are doing an why we are looking for this information? Head to the [Circle of Life](https://www.breakinggoodproject.com/circle-of-life) page on the Breaking Good website or read about about the research in a blog post by Kym Scroggie - [Cycloserine is available, but is it accessible?](https://www.breakinggoodproject.com/blog/2020/6/22/cycloserine-is-available-but-is-it-accessible)
