### ISSUE TITLE
Extending Stage I to Australia

### ISSUE THREAD

**Issue by yaelago** [TheBreakingGoodProject/Essential-Medicines#7]
Its time to expand E$$ENTIAL MEDICINE$ to include information on the accessibility of medicines beyond the USA. Australia here we come!!!
We will holding a **community meeting** to discuss the possibilities to automate data collection, and would love to hear from you. Optional dates for the meeting are:
- Thursday 9 July 8AM AEST (Wednesday 8 July 6PM EST)
- Thursday 9 July 9PM AEST (7 AM GMT EST)
- Monday 13 July 8AM AEST (Sunday 12 July 6PM EST)
- Monday 13 July 9PM AEST (7 AM GMT EST)

We've taken in consideration time differences between Australia and the USA, but if you live in a different location and would like to join, feel free to offer an additional time. 
Details on final timing and methods for communication will be sent once we've confirmed a time.

**Comment by Ecaloota** [comment]
Hi @yaelago; I am happy to join a meeting at any of the listed times but would prefer 9 PM on either 09/07 or 13/07 (DD/MM).

**Comment by kym834** [comment]
Thanks for getting back to us with your preferred time @Ecaloota.
We have tentatively locked in Monday 13 July 9PM AEST. 
If anyone else has another preference please let us know. We would like to share the finalised details for the community meeting on Friday 10 July.

**Comment by alintheopen** [comment]
Closing and moving to #8
