### ISSUE TITLE
Community Meeting (Technical) - Essential Medicines: Monday 13 July 2020

### ISSUE THREAD

**Issue by alintheopen** [TheBreakingGoodProject/Essential-Medicines#8]
Monday 13 July 9PM AEST (12 PM BST, 7 AM GMT EST)
Duration 1 hour

Hi all we warmly welcome you to our first Community Meeting for E$$ENTIAL MEDICINE$ - this time its a technical addition. Everyone is welcome and particularly coders and database experts. As mentioned in #7 

**Meeting Purpose**
To determine if automation is possible for Stage I E$$ENTIAL MEDICINE$, Australia

**Chair**
Alice Motion (@alintheopen )

Attendees (please add your name or reply below)
USYD: Hung Phat Duong @fantasy121 (Minutes), Yaela Golumbic @yaelago, Kymberley Scroggie @kym834 

**Hosted**
Meeting URL: | https://uni-sydney.zoom.us/j/95182245803
Meeting ID: | 951 8224 5803

The meeting will be recorded and chat and minutes uploaded to GitHub after the meeting.

**Agenda**

- Brief Project Update
- Discussion of Stage I Goals (EM Australia)
- Discussion of database requirements
- Discussion of automation possibilities
- AOB
- Next Steps and Action Items

**Comment by darwinyfu** [comment]
Hi! I'm interested in potentially helping with the Breaking Good automation project (saw this link on Twitter). Is there any bit of code/work I should review before jumping on the call? I've looked through the Stage I/II information for US malaria meds

**Comment by borawl** [comment]
I'll be there for the meeting!

**Comment by yaelago** [comment]
Hi @darwinyfu, great to hear of your interest, and thanks so much!
Stage I in the USA was automated thanks to the help of people in this group, see #2 for reference. We are now going forward with a similar process of data collection in Australia, however since the data sources are different, a new strategy is in place.
In the meeting, we will present potential data sources and discuss automation possibilities.
Looking forward to seeing you on the call!

**Comment by Ecaloota** [comment]
I'll be there too

**Comment by fantasy121** [comment]
Minutes for 13th July Meeting [here](https://github.com/TheBreakingGoodProject/Essential-Medicines/issues/10)
[E_20200713_Minute_DUONG.docx](https://github.com/TheBreakingGoodProject/Essential-Medicines/files/4923121/E_20200713_Minute_DUONG.docx)

Meeting Recording [here](https://www.youtube.com/watch?v=EnMjfFkHChs&feature=youtu.be)

**Comment by kym834** [comment]
Hi All, Thanks to everyone who was able to join us in our first community meeting for E$$ENTIAL MEDICINE$. It was great to meet and chat with you! 

@fantasy121 has shared the recording of the meeting that is now up on youtube and the minutes he kindly took during the meeting above.

The next meeting will be held in two weeks time on Monday 27 July 2020, tentatively arranged for 9PM AEST (12 PM BST, 7 AM GMT EST). A new issue has been created for this community meeting (https://github.com/TheBreakingGoodProject/Essential-Medicines/issues/9). Please head on over for more details!

**Comment by kym834** [comment]
@Ecaloota I've had a search for other resources besides the Australian Therapeutic Good Register but come up empty handed. How are thing going on your end regarding the possibility of being able to automate the data collection from their website?

**Comment by Ecaloota** [comment]
Hi @kym834, I didn't see this reply until this morning. I've written up my progress in #11.
