### ISSUE TITLE
Community Meeting (Technical #2) - Essential Medicines: Monday 27 July 2020

### ISSUE THREAD

**Issue by kym834** [TheBreakingGoodProject/Essential-Medicines#9]
Hi All :wave:

Our next community will be held on **Monday 27 July 9PM AEST** (12 PM BST, 7 AM GMT EST). This is a continuation from our first meeting (see https://github.com/TheBreakingGoodProject/Essential-Medicines/issues/8)

**Chair**
Alice Motion (@alintheopen )

**Attendees** (please add your name or reply below)
USYD: Hung Phat Duong @fantasy121 (Minutes), Yaela Golumbic @yaelago, Kymberley Scroggie @kym834

**Hosted**
Meeting URL: | https://uni-sydney.zoom.us/j/95182245803
Meeting ID: | 951 8224 5803

The meeting will be recorded and chat and minutes uploaded to GitHub after the meeting.

**Agenda** 

- Update on last meeting action items
- Update on resources and automation status
- Next steps and action items - 
Where automation is possible, who can help, what additional resources or assistance is needed?
Where automation is not possible, what is the best method for data collection?
- Update on national science week activities.
- AOB

**Comment by narath** [comment]
So glad there is lots of progress being made. Unfortunately I will not be able to join, but will look forward to the meeting minutes.

**Comment by kym834** [comment]
The post above has now been updated with an agenda and meeting URL and ID for our community meeting that will be held next week. Please let us know if you will be joining us 😃 

@narath, thanks for keeping with the project! We are also excited about all the progress. Hopefully you will be able to join us at a later meeting.

**Comment by Ecaloota** [comment]
Hi @kym834, just letting you know that I'll be at the meeting today / this evening. See you then!
